const imageByType = {
  Bus: '/bus-ticket.png',
  Train: '/train-ticket.png',
  Flight: '/flight-ticket.png',
  Launch: '/launch-ticket.png',
}

export const tickets = [
  {
    id: 1,
    image: imageByType.Bus,
    title: 'Hanif Enterprise Deluxe',
    from: 'Dhaka',
    to: 'Chattogram',
    type: 'Bus',
    price: 12,
    date: 'Jun 24, 2026',
    departure: '08:30 AM',
    departureMinutes: 510,
    duration: '6h 15m',
    seats: 5,
    rating: 4.8,
    perks: ['WiFi', 'AC', 'Snacks'],
    featured: true,
  },
  {
    id: 2,
    image: imageByType.Train,
    title: 'Parabat Express',
    from: 'Dhaka',
    to: 'Sylhet',
    type: 'Train',
    price: 18,
    date: 'Jun 24, 2026',
    departure: '09:15 AM',
    departureMinutes: 555,
    duration: '5h 40m',
    seats: 8,
    rating: 4.9,
    perks: ['Dining', 'Sleeper', 'Charging'],
    featured: true,
  },
  {
    id: 3,
    image: imageByType.Flight,
    title: 'US-Bangla Airlines',
    from: 'Dhaka',
    to: "Cox's Bazar",
    type: 'Flight',
    price: 45,
    date: 'Jun 25, 2026',
    departure: '10:00 AM',
    departureMinutes: 600,
    duration: '1h 05m',
    seats: 12,
    rating: 4.9,
    perks: ['Meals', 'Luggage', 'Priority'],
    featured: true,
  },
  {
    id: 4,
    image: imageByType.Launch,
    title: 'Sundarban Launch',
    from: 'Dhaka',
    to: 'Barishal',
    type: 'Launch',
    price: 15,
    date: 'Jun 25, 2026',
    departure: '07:00 AM',
    departureMinutes: 420,
    duration: '8h 30m',
    seats: 20,
    rating: 4.7,
    perks: ['Deck Views', 'Café', 'Cabin'],
  },
  {
    id: 5,
    image: imageByType.Bus,
    title: 'Green Line Volvo',
    from: 'Chattogram',
    to: 'Sylhet',
    type: 'Bus',
    price: 14,
    date: 'Jun 26, 2026',
    departure: '06:30 AM',
    departureMinutes: 390,
    duration: '7h 20m',
    seats: 3,
    rating: 4.6,
    perks: ['WiFi', 'AC', 'USB'],
  },
  {
    id: 6,
    image: imageByType.Train,
    title: 'Sonar Bangla Express',
    from: 'Sylhet',
    to: "Cox's Bazar",
    type: 'Train',
    price: 22,
    date: 'Jun 26, 2026',
    departure: '11:45 AM',
    departureMinutes: 705,
    duration: '9h 10m',
    seats: 6,
    rating: 4.8,
    perks: ['Dining', 'AC', 'Charging'],
  },
  {
    id: 7,
    image: imageByType.Flight,
    title: 'Biman Bangladesh',
    from: 'Dhaka',
    to: 'Saidpur',
    type: 'Flight',
    price: 52,
    date: 'Jun 27, 2026',
    departure: '02:30 PM',
    departureMinutes: 870,
    duration: '0h 55m',
    seats: 9,
    rating: 4.7,
    perks: ['Meals', 'Luggage', 'Lounge'],
  },
  {
    id: 8,
    image: imageByType.Launch,
    title: 'Surovi Paribahan',
    from: 'Dhaka',
    to: 'Bhola',
    type: 'Launch',
    price: 11,
    date: 'Jun 27, 2026',
    departure: '06:00 PM',
    departureMinutes: 1080,
    duration: '10h 00m',
    seats: 25,
    rating: 4.5,
    perks: ['Cabin', 'Café', 'Deck'],
  },
  {
    id: 9,
    image: imageByType.Bus,
    title: 'Shyamoli NR Travels',
    from: 'Dhaka',
    to: 'Rajshahi',
    type: 'Bus',
    price: 16,
    date: 'Jun 28, 2026',
    departure: '11:00 PM',
    departureMinutes: 1380,
    duration: '6h 45m',
    seats: 7,
    rating: 4.6,
    perks: ['WiFi', 'AC', 'Blanket'],
  },
  {
    id: 10,
    image: imageByType.Train,
    title: 'Padma Express',
    from: 'Dhaka',
    to: 'Khulna',
    type: 'Train',
    price: 20,
    date: 'Jun 28, 2026',
    departure: '08:00 AM',
    departureMinutes: 480,
    duration: '7h 30m',
    seats: 14,
    rating: 4.8,
    perks: ['Dining', 'Sleeper', 'AC'],
  },
  {
    id: 11,
    image: imageByType.Flight,
    title: 'Novoair Express',
    from: 'Chattogram',
    to: 'Jessore',
    type: 'Flight',
    price: 60,
    date: 'Jun 29, 2026',
    departure: '04:15 PM',
    departureMinutes: 975,
    duration: '1h 20m',
    seats: 4,
    rating: 4.9,
    perks: ['Meals', 'Priority', 'Lounge'],
  },
  {
    id: 12,
    image: imageByType.Bus,
    title: 'Ena Transport',
    from: 'Sylhet',
    to: 'Dhaka',
    type: 'Bus',
    price: 13,
    date: 'Jun 29, 2026',
    departure: '09:30 PM',
    departureMinutes: 1290,
    duration: '6h 00m',
    seats: 11,
    rating: 4.5,
    perks: ['WiFi', 'AC', 'Snacks'],
  },
]
